name_map = {
    "bridge_carrot_generated_modified": "carrot",
    "bridge_plate_objaverse_larger": "plate",
    "pepsi_can": "pepsi can",
    "apple": "apple",
    "orange": "orange",
    "eggplant": "eggplant",
    "011_banana": "banana",
    "table_cloth_generated_shorter": "towel",
    "bridge_spoon_generated_modified": "spoon",
    "blender_car": "car",
    "blender_duck": "duck",
    "blender_pitaya": "pitaya",
    "blender_baby_bottle": "baby bottle",
    "blender_croissant": "croissant",
    "blender_cucumber": "cucumber",
    "blender_maize": "maize",
    "blender_shaver": "shaver",
    "blender_tomato": "tomato",
    "blender_rubik_cube": "rubik's cube",
    "blender_bear": "teddy bear",
    "blender_watermelon": "watermelon",
    "blender_bin1": "bin",
}
